apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-capstone
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/VickyCloud17/devops-capstone.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
